INSERT INTO TB_DEPARTMENT (NAME) VALUES ('TECH');
INSERT INTO TB_DEPARTMENT (NAME) VALUES ('PET');

INSERT INTO TB_PRODUCT (NAME,PRICE,DEPARTMENT_ID) VALUES ('MACBOOK PRO', 4000.0, 1);
INSERT INTO TB_PRODUCT (NAME,PRICE,DEPARTMENT_ID) VALUES ('PC GAMER', 5000.0, 1);
INSERT INTO TB_PRODUCT (NAME,PRICE,DEPARTMENT_ID) VALUES ('PET HOUSE', 4000.0, 2);